<?php

namespace App;

use App\Route\IndexRoute;
use Kod\BootstrapSlim\Bootstrap as BootstrapSlim;

/**
 * Bootstrap
 */
class Bootstrap extends BootstrapSlim
{

    public function addAppMiddleware()
    {
        return parent::addAppMiddleware(); // TODO: Change the autogenerated stub
    }

    public function addAppRoutes()
    {
        $this->addRouteDefinitions(
            IndexRoute::class
        );
    }
}
